### ISSUE TITLE
Do not reorder side effect imports

### ISSUE THREAD

**Issue by blutorange** [trivago/prettier-plugin-sort-imports#110]
Apologies if this has been mentioned already, I did not find any issue for, though.

**Is your feature request related to a problem?**

A [side effect import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only) is an import that only imports a module for its side effects, without importing any values. These are currently sorted just like any other imports. Since those imports are explicitly used for side-effects, changing the order will usually result in a different behavior.

Now side effects are something that should be avoided if possible, and library code should have side effects. However, there are some valid use cases, such as loading mocks for tests, [mock-fs](https://github.com/tschaub/mock-fs/blob/main/readme.md#caveats) or loading global libraries in an index file of a wep app, etc. For example:

```
import "./setup-test-environment"; // setup some required globals on which some module rely unfortunately
import { something } from "./a-module-to-test";
```

The above would be re-ordered, which breaks the test.

**Describe the solution you'd like**

Side effect imports should not be reordered. [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md) does not reorder them either, for the same reason.

Since it is hard to know which side effect imports affect which other imports, I would suggest the following solution: treat a side effect import as a boundary that splits the imports into two groups, the imports before the the side effect import and the imports after the side effect import. Then only sort the imports before and after the side effect import as you would normally. This is I think the easiest to implement and also the safest. If users want to have side effect at the top, they can just move the side effect imports to the top, and the formatter will leave them there.

I made this a feature, but I would almost consider it a bug. By default, side effect imports should not be reordered. An option could be added for sorting these imports too, but I'm not sure if that's really necessary.

So for example:

```javascript
// Side effect import 1
import "S1";

// Start group 1
import {} from "b";
import * as A from "c";
// End group 1

// Side effect import 2
import "S2";

// Start group 2
import foo from "d";
import { bar } from "e";
// End group 2

// Side effect import 3
import "S3";
```

In the example above, keep the side effect imports as they are. Sort the imports in group 1 and group 2 using whatever options are set. *Do not* move any import from group 1 to group 2 or vice-versa.

**Describe alternatives you've considered**

Another alternative I can think of is to simply keep the relative ordering of the side effect imports, but allow moving non side effect imports anywhere. Or always just put side effect imports at the top. Both of this possibilities have the disadvantage they the may be unsafe: putting an import from before a side effect import after it may break it because it does not expect that side effect; putting an import from after a side-effect before it may break it because it relies on the side effect. It's also unclear how imports with and without side effects should be ordered relatively to each other.

**Comment by blutorange** [comment]
Might be related to or possibly solve #95, though I'm not sure if they're talking about CSS imports in JavaScript/TypeScript files or `@import` in CSS/SCSS files.

**Comment by artola** [comment]
@blutorange Same for me. We would like to use this plugin, but the ordering must be "perfect", as the users do not expect their code to break unexpectedly just because of saving a file for example.

**Comment by NiklasPor** [comment]
Same for us, I just crashed all of our unit tests because for our jest setup we need a specific import order: https://github.com/nrwl/nx/issues/6361#issuecomment-994922109.

Also, I didn't find any workaround, except adding those files to the .prettierignore.

**Comment by artola** [comment]
@ayusharma This bug is really a showstopper, sometimes for a few files you can use @NiklasPor workaround mentioned above, but it does not scale when you run a huge codebase with many devs that should be aware, making the code really fragile.
If a test breaks, probably you will find it early, but if the change is more subtle, like CSS order, then it will go direct on your face.

**Comment by blutorange** [comment]
These issues make me wonder if anybody who's using this plugin actually has any side effect imports in files that are not in the .prettierignore. If nobody does, then #111 wouldn't even affect existing users.

**Comment by artola** [comment]
@blutorange #111 is great solution. Thanks! Now I hope to get Trivago's team support to get this bug solved.

**Comment by NiklasPor** [comment]
Actually, our workaround looks now a bit different. I just overwrote the sorting order for those specific files. Still **not** a great solution:

```js
// prettierrc.js
overrides: [
    {
      files: 'test-setup.ts',
      options: {
        importOrder: ['jest.*', '<THIRD_PARTY_MODULES>'],
      },
    },
  ]
```

**Comment by DavidArmendariz** [comment]
Has this issue being solved?

**Comment by blutorange** [comment]
The current state of the issue, as far as I know, is that it's not a bug and also working as intended. There was the suggestion to add an option (disabled by default) that enables #111. If anybody wants to take that PR and add said option, feel free to, but personally I'm not interested in a solution that is "broken" by default. Perhaps somebody else has an idea how to solve this in a way that can be enabled by default?

**Comment by artola** [comment]
@blutorange is it time to fork?

**Comment by IanVS** [comment]
I think that #111 is an important bugfix, and that this plugin is not suitable for production use without it.  So, I've published a fork which is currently the same as this package, but with https://github.com/trivago/prettier-plugin-sort-imports/pull/111 included (without any kind of option necessary).  It can be found at https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports for anyone else who might find it useful.

**Comment by ianldgs** [comment]
Just had some annoying CSS issues because the import of the library's CSS was moved to after our custom style overrides.
Love this library, but it doesn't make sense for us to ignore prettier completely for a file just because of the imports. Will move to the fork while this issue is not resolved.

**Comment by cvolant** [comment]
We moved too for the exact same reason.

**Comment by Morriz** [comment]
Any forward motion towards unifying these efforts? Can #111 not be merged or reworked? Or @IanVS's fork be merged into this one? It sux to have a whole fork for what is in essence a bug, as this plugin is unreliable without the fix.

@blutorange it seems you are most involved with this, so may I ask what is the blocker here?

**Comment by blutorange** [comment]
@Morriz The blocker is that the maintainers of this project consider this bug fix as ["it fails the basic idea of the plugin"](https://github.com/trivago/prettier-plugin-sort-imports/pull/111#issuecomment-1016310310)

**Comment by IanVS** [comment]
@Morriz FWIW, my fork now has a few features that this project does not have, and gets a fair number of npm downloads.  I use it in a few of my own projects, and continue to maintain it.  In case that eases your mind about using a fork.
